<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // ============ ПОЛЬЗОВАТЕЛИ ============
        DB::table('users')->insert([
            [
                'name' => 'Administrator',
                'login' => 'admin',
                'pass' => md5('admin123'),
                'role' => 1, // администратор
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Иван Петров',
                'login' => 'ivan',
                'pass' => md5('password123'),
                'role' => 0, // обычный пользователь
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Мария Сидорова',
                'login' => 'maria',
                'pass' => md5('password456'),
                'role' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============ ОБЪЕКТЫ (ДОМА/ЗДАНИЯ) ============
        DB::table('objects')->insert([
            [
                'address' => 'ул. Главная 123',
                'City' => 'Таллин',
                'GSMNR' => '+37259123456',
                'IMEI' => '862049044965471',
                'IMEI2' => '862049044965472',
                'Contact' => 'Иван Петров',
                'Description' => '5-этажный жилой дом, 32 квартиры',
                'Description2' => 'Год постройки: 1995',
                'Company' => 1,
                'dtype' => 1,
                'status' => 1,
                'Devqtty' => 8,
                'RadioDevQty' => 3,
                'MainRadio' => 1,
                'GSMSERIAL' => 'GSM001',
                'GSMSERIAL2' => null,
                'pin1' => null,
                'pin2' => null,
                'puk1' => null,
                'puk2' => null,
                'KeyCode' => null,
                'manager' => 1,
                'packet' => 'standard',
                'traffic' => '100MB',
                'callCnt' => 50,
                'summ' => 250.00,
                'ver' => 2,
                'lastSession' => now(),
                'selDate' => null,
                'lat' => 59.4370,
                'lon' => 24.7536,
                'saveHval' => true,
                'm2_andur' => 2500,
                'dataToPage' => true,
                'AddFee' => 5.00,
                'fee' => 25.00,
                'kuluM2' => 1.50,
                'AlgLopp' => 1,
                'created_at' => now()->subDays(30),
                'updated_at' => now(),
            ],
            [
                'address' => 'ул. Парковая 45',
                'City' => 'Таллин',
                'GSMNR' => '+37259234567',
                'IMEI' => '862049044965473',
                'IMEI2' => null,
                'Contact' => 'Мария Сидорова',
                'Description' => '3-этажный жилой дом, 12 квартир',
                'Description2' => null,
                'Company' => 1,
                'dtype' => 3,
                'status' => 1,
                'Devqtty' => 5,
                'RadioDevQty' => 2,
                'MainRadio' => 0,
                'GSMSERIAL' => 'GSM002',
                'GSMSERIAL2' => null,
                'pin1' => null,
                'pin2' => null,
                'puk1' => null,
                'puk2' => null,
                'KeyCode' => null,
                'manager' => 2,
                'packet' => 'premium',
                'traffic' => '200MB',
                'callCnt' => 75,
                'summ' => 180.00,
                'ver' => 1,
                'lastSession' => now()->subHours(2),
                'selDate' => null,
                'lat' => 59.4380,
                'lon' => 24.7540,
                'saveHval' => false,
                'm2_andur' => 800,
                'dataToPage' => false,
                'AddFee' => 0,
                'fee' => 18.00,
                'kuluM2' => 0,
                'AlgLopp' => 0,
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subDays(5),
            ],
            [
                'address' => 'ул. Лесная 78',
                'City' => 'Таллин',
                'GSMNR' => '+37259345678',
                'IMEI' => '862049044965474',
                'IMEI2' => null,
                'Contact' => 'Петр Иванов',
                'Description' => 'Коммерческое здание, офисы',
                'Description2' => null,
                'Company' => 2,
                'dtype' => 2,
                'status' => 1,
                'Devqtty' => 3,
                'RadioDevQty' => 0,
                'MainRadio' => 0,
                'GSMSERIAL' => 'GSM003',
                'GSMSERIAL2' => null,
                'pin1' => null,
                'pin2' => null,
                'puk1' => null,
                'puk2' => null,
                'KeyCode' => null,
                'manager' => 3,
                'packet' => 'basic',
                'traffic' => '50MB',
                'callCnt' => 30,
                'summ' => 120.00,
                'ver' => 3,
                'lastSession' => now()->subDays(1),
                'selDate' => null,
                'lat' => 59.4400,
                'lon' => 24.7550,
                'saveHval' => false,
                'm2_andur' => 0,
                'dataToPage' => false,
                'AddFee' => 0,
                'fee' => 12.00,
                'kuluM2' => 0,
                'AlgLopp' => 0,
                'created_at' => now()->subDays(90),
                'updated_at' => now()->subDays(10),
            ],
            [
                'address' => 'ул. Цветочная 12',
                'City' => 'Таллин',
                'GSMNR' => '+37259456789',
                'IMEI' => '862049044965475',
                'IMEI2' => null,
                'Contact' => 'Ольга Козлова',
                'Description' => 'Многоквартирный дом с отоплением',
                'Description2' => null,
                'Company' => 1,
                'dtype' => 3,
                'status' => 1,
                'Devqtty' => 12,
                'RadioDevQty' => 5,
                'MainRadio' => 1,
                'GSMSERIAL' => 'GSM004',
                'GSMSERIAL2' => null,
                'pin1' => null,
                'pin2' => null,
                'puk1' => null,
                'puk2' => null,
                'KeyCode' => null,
                'manager' => 1,
                'packet' => 'premium',
                'traffic' => '300MB',
                'callCnt' => 100,
                'summ' => 350.00,
                'ver' => 2,
                'lastSession' => now(),
                'selDate' => null,
                'lat' => 59.4420,
                'lon' => 24.7560,
                'saveHval' => true,
                'm2_andur' => 5000,
                'dataToPage' => true,
                'AddFee' => 10.00,
                'fee' => 35.00,
                'kuluM2' => 2.00,
                'AlgLopp' => 1,
                'created_at' => now()->subDays(45),
                'updated_at' => now(),
            ],
        ]);

        // ============ ДАННЫЕ УСТАНОВКИ ПРИБОРОВ ============
        DB::table('objects_install_data')->insert([
            [
                'oid' => 1,
                'devid' => 1001,
                'location' => 'Подвал, стояк 1',
                'devtype' => 1,
                'dnType' => 20,
                'len' => 50,
                'foto1' => 1,
                'foto2' => 1,
                'place1' => 'Подвал',
                'place2' => 'Холодное водоснабжение',
                'comment' => 'Установлен 15.01.2024',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'oid' => 1,
                'devid' => 1002,
                'location' => 'Подвал, стояк 2',
                'devtype' => 1,
                'dnType' => 20,
                'len' => 50,
                'foto1' => 0,
                'foto2' => 0,
                'place1' => 'Подвал',
                'place2' => 'Горячее водоснабжение',
                'comment' => 'Установлен 15.01.2024',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'oid' => 2,
                'devid' => 2001,
                'location' => 'Электрощитовая',
                'devtype' => 3,
                'dnType' => 0,
                'len' => 30,
                'foto1' => 0,
                'foto2' => 0,
                'place1' => '1-й этаж',
                'place2' => null,
                'comment' => 'Трехфазный счетчик',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'oid' => 3,
                'devid' => 3001,
                'location' => 'Газовая котельная',
                'devtype' => 2,
                'dnType' => 15,
                'len' => 25,
                'foto1' => 0,
                'foto2' => 0,
                'place1' => 'Подвал',
                'place2' => null,
                'comment' => 'Газовый счетчик объемный',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'oid' => 4,
                'devid' => 4001,
                'location' => 'Техподвал',
                'devtype' => 3,
                'dnType' => 0,
                'len' => 40,
                'foto1' => 0,
                'foto2' => 0,
                'place1' => 'Техническое помещение',
                'place2' => null,
                'comment' => 'Главный счетчик',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============ ЛОГИРОВАНИЕ ============
        DB::table('log')->insert([
            [
                'Content' => 'User admin logged in from 192.168.1.100',
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'Content' => 'Object #1 updated: last session updated',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'Content' => 'New device added to object #1: devid=1001',
                'created_at' => now()->subHours(1),
                'updated_at' => now()->subHours(1),
            ],
            [
                'Content' => 'Data export requested for object #2',
                'created_at' => now()->subMinutes(30),
                'updated_at' => now()->subMinutes(30),
            ],
            [
                'Content' => 'System backup completed successfully',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Content' => 'User maria logged in from 192.168.1.50',
                'created_at' => now()->subMinutes(15),
                'updated_at' => now()->subMinutes(15),
            ],
        ]);

        // ============ КАЧЕСТВО СИГНАЛА GSM ============
        DB::table('csq')->insert([
            [
                'object' => 1,
                'csq' => 25,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'object' => 1,
                'csq' => 28,
                'created_at' => now()->subHours(4),
                'updated_at' => now()->subHours(4),
            ],
            [
                'object' => 1,
                'csq' => 26,
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'object' => 1,
                'csq' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'object' => 2,
                'csq' => 22,
                'created_at' => now()->subHours(5),
                'updated_at' => now()->subHours(5),
            ],
            [
                'object' => 2,
                'csq' => 20,
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'object' => 3,
                'csq' => 31,
                'created_at' => now()->subHours(4),
                'updated_at' => now()->subHours(4),
            ],
            [
                'object' => 4,
                'csq' => 27,
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
        ]);
    }
}
